version: "3"
services:
    nextjs:
        container_name: ${PROJECT_NAME}-nextjs
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        volumes:
            - .:/usr/app/
            - ./node_modules/:/usr/app/node_modules
        ports:
            - 4000:4000
            # - 9231:9229
        environment:
            - VIRTUAL_HOST=${PROJECT_NAME}.lol
            - VIRTUAL_PORT=4000
        network_mode: "bridge"

    # Only used to install vendors
    vendors:
        build:
            context: ./
            dockerfile: ./docker/install/Dockerfile
        container_name: ${PROJECT_NAME}-vendors-front
        volumes:
            - .:/usr/app/
            - ./node_modules/:/usr/app/node_modules
